# This is a TOML document

title = "repapr-ppo config file"

[input] # 入力変数
tones = 4
del_freq = 1.0
del_time = 0.001
amp = 1.0
init_model = "narahashi"
manual = []

[addproc] # 追加処理
inf_calc = true
inheritance_theta_k = true
inheritance_reset = false
shrink_action_div = true
load_data = false
overwrite = false
rt_graph = false
notify = false

[env.observation]
theta_k = true
papr_db = true
action_div = true
peaks_height = false        # calc_peaks
len_both_peaks = false      # calc_peaks
reward = true

[env.reward]
eval_metrics = "mse"
eval_model = "AMSE_v0"

[env.param] # 環境パラメータ
n_calc = 300                    # 計算上限
n_inherit = 30                  # 継承上限
max_step = 20#*tones            # 1エピソードあたりのステップ上限
action_div = 0.02               # 初期行動倍率 (値を大きくしすぎると大雑把になる)
action_div_shrink_scale = 0.9   # 行動倍率を縮小させる倍率
action_list = [-1, 0, 1]        # 行動の選択肢

[hyper] # ハイパーパラメータ
N = 10
batch_size = 5
n_epochs = 4
alpha = 0.0003

[score] # スコア処理パラメータ
avg_init = 25
avg_calc = 50

[output]
filepath = "repapr-ppo/out"

[output.line]
channel_token = ""
user_id = ""