# This is a TOML document

title = "repapr-ppo config file"

[input] # 入力変数
tones = 4
del_freq = 1.0
del_time = 0.002
amp = 1.0
init_model = "all0"
manual = []

[addproc] # 追加処理
ignore_n_epi = true
inheritance_theta_k = true
inheritance_reset = false
shrink_action_div = true
load_data = false
overwrite = false
rt_graph = false
notify = false

[env.observation]
theta_k = true
papr_db = true
action_div = true
peaks_height = false        # calc_peaks
len_both_peaks = false      # calc_peaks
reward = false

[env.reward]
eval_metrics = "mse"
eval_model = "AMSE_v0"

[env.param] # 環境パラメータ
n_calc = 100000                 # 計算上限 (ignore_n_epiがTrueでも有効)
n_inherit = 70                  # 継承上限
max_step = 5#*tones             # 1エピソードあたりのステップ上限
action_div = 0.25               # 初期行動倍率 (値を大きくしすぎると大雑把になる)
action_div_shrink_scale = 0.875 # 行動倍率を縮小させる倍率
action_list = [-1, 1]           # 行動の選択肢

[hyper] # ハイパーパラメータ
N = 32
batch_size = 4
n_epochs = 3
alpha = 7e-5

[score] # スコア処理パラメータ
avg_init = 25
avg_calc = 10

[output]
filepath = "repapr-ppo/out"

[output.line]
channel_token = ""
user_id = ""